### ISSUE TITLE
it doest work when deployed on linux server even in debug mode

### ISSUE THREAD

**Issue by blue-nothing** [danielenricocahall/dash-recording-components#1]
i have tried to deploy my demo on my linux server with the component you provided,thanks first.but it doest work on my server. when i use it locally,it can work fine.

**Comment by danielenricocahall** [comment]
Hi @blue-xu-blue , do you have some more details on the problem that may make it easier to reproduce and diagnose the problem?

**Comment by blue-nothing** [comment]
My program startup entrance
![屏幕截图 2024-03-12 111522](https://github.com/danielenricocahall/dash-recording-components/assets/60543667/6ca982fb-da2b-45ee-a6ec-780ceec809ac)
Start recording and stop recording, and print the results on the backend console
![屏幕截图 2024-03-12 111507](https://github.com/danielenricocahall/dash-recording-components/assets/60543667/4db2b030-f70a-4077-8366-f720df3c6e10)
But when I clicked to record, the browser did not pop up a recording prompt, indicating that it did not take effect at all.

**Comment by blue-nothing** [comment]
I think I have got the right solution to solve this problem. The reason why It doesnt work is that  brower's security policy. so just to enable the switch and fill in the target ip . 
just text this at your browser: edge://flags/#unsafely-treat-insecure-origin-as-secure, and filter some ip
